### ISSUE TITLE
Take number of events into account for `_compute_time_intervals_based_on_fov_rotation`

### ISSUE THREAD

**Issue by StFroese** [mdebony/acceptance_modelisation#7]
I really like the idea of using the FoV rotation to calculate the time frame in which to evaluate the observations 😊 
Unfortunately I came across the problem that this can fail in the case that the time frame is so small that there are no events in the sub-observation you are looking at. 
I guess one solution would be to check the number events for the time frame but this requires to do `obs.select_time()` inside the `_compute_time_intervals_based_on_fov_rotation` method. The other solution would be to required something like a `deltaT_threshold` so that there are no frames that have smaller duration than this threshold :)

**Comment by StFroese** [comment]
This fails here
https://github.com/mdebony/acceptance_modelisation/blob/c6ae04e0b708bc68d7620444c86073b48ffbea2f/acceptance_modelisation/base_acceptance_map_creator.py#L102

Another solution would be to check if `obs.events.time` is empty and skip by just returning an observation with null data

**Comment by mdebony** [comment]
Thanks for the feedback. I think the best would be to handle it at the time of creating the internal map itself. Removing observation chunk could in the end bias the exposure estimation and so the normalization of the final model.

**Comment by mdebony** [comment]
@gabemery Could you confirm this is fixed ?

**Comment by gabemery** [comment]
@mdebony  Yes it is. I close the issue.
